id: IE312E811
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-14T12:28:09+00:00'
last_modified: '2022-06-15T16:55:28.970350+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27495
  title: གསོ་རིག་ཉེར་མཁོ་གཅེས་བསྡུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4243':
      image_group_id: I4745
      title: ''
      total_pages: 512
      order: 1
      base_file: 4243.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
